{% set name = "paramz" %}
{% set version = "0.9.1" %}
{% set sha256 = "8a5a2fe5cdb033eb869c49e81fde2a9d0055fadb53a8af1665a7f48f320179cf" %}


package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy >=1.7
    - scipy
    - six
    - decorator >=4.0.10
test:
  imports:
    - paramz

about:
  home: https://github.com/sods/paramz
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Parameterization Framework for parameterized model creation and handling.'
  doc_url: https://pythonhosted.org/paramz
  dev_url: https://github.com/sods/paramz

extra:
  recipe-maintainers:
    - dirmeier
