travis:
  secure:
    BINSTAR_TOKEN: ONEVDXiy49Fnrciv7dN6sXBiFqVOAe6uBPvVaW7U3kNiIhYIPlk7fzNltZX6Y6ZkyXd9faTkIC7uOfXA8nAWRwexrNFFHeSJ5xGiOShgWU5meWjy4aX9uc6U6T8EIQXx5bTXcu3k3Lt9tbKYcwPYtvra619WxWaY3nWAehuWIWNZLtLFkl6Yt+oSoOjxM7eT8JEAEDWzkT5StsxteebFziEOfszCZ7SCh4eO6Alb628iFCHCt2B9JyJn0WLh/qIGRYszvMHcbyfq6ecpNYnBBRA4WMAB3KxUKS3Ov4HMB4UvL9xY8cY1el+CEx7RRMtuyMsJbsLMUIPRRiPSa1jOIhLJQhSJEkNh9K4Y4Q6PTyJQahuzM0TbgttuIMVJQITYpOxc9FTI1U9KbQPK0950urNqcQn9prD1+lVyIthIA3vwRAOpaIG+Ohhoo+3qEDqPnKFd/U5orgjB6xSevTLeXByKqs5QC0fxaHQ7+MbPdI+Q15uL0xcGx9oiBzX6WeoAbrq7vUkaADnweELJMPTXMzSjUZSUsFWyWPAoclsdpb08wYRaz4nSTEJgsEVkAK3a2223IaAAFWhFRp64yh7ekHcIIw49ULqOr8Q9d4fhKD26gvP3JcFuaUqau9Wbsbzc6XdLAIUceMtvbCXJIsU+Jn0N21RVAJqxdhgxoT/aP28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
