travis:
  secure:
    BINSTAR_TOKEN: Ul2BLs5hjaCje7/mjHxGhG7VMkC5d/4RL0vYxBqHd0UBoGyjKl/ZAx4AMDGPp1JQNsUhjTFqXDB9w6rLDFWDPVespJqZXus8H5E6tuXkxACxMcGI6E4QJB0QuDUKuxhTd8pr0l2pFZTTqv7+NJePw6143MPNcvlJ7nX1dniike8WdrxTXSG7w5AQcnW/TQejGszlLcG90tsRF+/7QHRr3W1amK882YKTYeR0NzNLvRb79iIdgd/mdez6j88vB6UsOxbeSkAtXiW2UVYKzyw1AtBIte6D+jdA2FOPcqHmraZFOL2IJ146oZEcmRj5dUuNki4LJV9fsKAlMZsLRY8EaEDjSTsJsnTIaFzMFmobropiJBcw+uf8JECAGSUdjH88WYEGJD0F26VlsOhcHFeTYtI6xTsFbhgD81mfwTHBKtgTtD+9civ6nsIfjGWyXJrovHsi0eujB0x1+haQfcQcVYqIijeWLTtCAS0BErGmKtEIkC88QWqBeGHIYP42DcMtmvNHP9EQ5o+A/w1I8yT/OG3uPJy9MKZDnCc+XQHiMEd+PMAy3whf4kQJRch5dw03/drRoVxCaCJex2fP86qJACFMNMB5EOa9KYZ0bttEgvcaoSR3iNu0U8g0687R8Y/r90RYNBk/jpH1LjmIdPQQrFHJFjLCmRhpjoP6IyOhoiU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
