travis:
  secure:
    BINSTAR_TOKEN: ohoVlktaXcVptKFPfOnvc8JfJvM6ZfvnooKEUTQOxjypVO76hJ/S2ZEvJcf1118ZylmLmD478wpLRxRVMJGwIIUo40alG+iRRwb1RKx2Beh5hiF30iveDnryuAOS5odjRTowMFzXa/u5+c6CgIxzDeXglm25rV4hrPplmUXruwpMwMc+3bKAHZ4lC19ExB7/UPWu711VN4hQBT5qCxYWY/97u5FpiU9vwJohMuiKAoGxBHMsXkdgGFiKA4iLjyZds3KHhb/0E9E22ng3fdlJsCeagvQMWxiQ10nmDnNLF+QnjKtjpXPvrSkvmM47E0ybaWIrQ1uDl949VPIhaGX8tDW+LUzVuPcK4Ur9zyDzqW4fvcK1eC/vgz9bb9jQRP9BxSVB7lJDIywp2xjufbfotYlLcsY5wfTsO/EvyFEzjojaxRlLdJpIi+vy769cv+iTPivmS35EoStWObVC/2BlQ42TFa6OFzjOONZ0iu0iRrwxtPtrDH+u1WuUPCV2Pp4IEG2GF2bD4rRJLkFNe+f1AmVSGOiFBaut57jhKuzww00UzRuU+rpz8L8z9n4Wi3MZw9pxWWNtIyxZDjVf3ondqI0Uxt0w7LzRSWLb479Ig3yyrreUlE07sr81JAIw+h92D9ta+D6+bJ1TeVYsBcfIDSX0mmyQdoHhZUcLjYJ73Hw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
